Mudule 2-2 Api models and dto mappers
vedmas/crowdproj-product-groups pull request #2
Opened 2023-02-26 09:11 UTC by vedmas

Api models and dto mappers

2023-02-26 17:51 UTC, svok requested changes
Алексей, все отлично, что у вас получилось. В принципе, этого достаточно для сдачи ДЗ. Для открытого проекта все-таки нужно учесть некоторые нюансы. Я прошу поправить их перед сведением в публичный проект.

2023-02-26 17:51 UTC, svok commented on api/src/main/kotlin/ApiMapper.kt
> +    configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
This option is better to be not used.
We have a contract through OpenAPI. There is no reason to appear for unspecified properties. If they do they need to be explored.

2023-02-26 17:51 UTC, svok commented on api/src/test/kotlin/RequestSerializationTest.kt
> +        assertContains(json, Regex("\"name\":\\s*\"ad title\""))
Triple quotes could simplify this notation.

2023-02-26 17:51 UTC, svok commented on common/build.gradle.kts
> +    macosX64 {}
На вэбинарах macos подключается из-за того, что у некоторых студентов и преподавателей именно эта ОС.
Если говорить про crowdproj, то вряд ли когда-либо потребуется мак для его работы. Все бэкенд приложения крутятся на Линуксе. Только будут лишние затраты на поддержку.

2023-02-26 17:51 UTC, svok commented on api/build.gradle.kts
> +}
Общие рекомендации по наименованию отписал в чате. Здесь дублирую.

Коллеги, проекты crowdproj будут публиковаться, в том числе в реестрах maven и docker. Поэтому прошу придерживаться определенных правил наименования.
1. groupId:artefactId. Сейчас у меня зарегистрирован groupId в mavenCentral com.crowdproj. Видимо нужно мне будет сделать отдельный com.crowdproj.marketplace. Но мне бы не хотелось регистрировать в мавен-центал каждый проект. Поэтому предлагаю нынешние проектам назначать следующие groupId:artifactId: com.crowdproj.marketplace:<your project>-<subproject>. Например, com.crowdproj.marketplace:product-group-api-v1
2. Пакеты должны соответствовать groupId и artefactId. Например, пакет для АПИ в1 должен быть следующий: com.crowdproj.marketplace.api.v1. Соответственно, полное имя класса будет com.crowdproj.marketplace.api.v1.ProductGroupsCreateRequest
3. Очень неудобно, когда разные классы называются одинаково. Например, на фронтенде нужно будет использовать IRequest для группы продуктов и свойтв продукта. Конечно, это не фатально, просто неудобно. Гораздо проще, когда классы называются по-разному, например, IProductGroupRequest, IProductPropertyRequest.

2023-02-26 17:51 UTC, svok commented on api/src/test/kotlin/ResponseSerializationTest.kt
> +import ru.otus.otuskotlin.marketplace.api.v1.models.*
Надо привести в один стиль. Большие буквы в пакетах приводят к мелким неожиданным проблемам. Поэтому следует всегда пакеты именовать с маленькой буквы, желательно без пунктуаций. Формально допустимы подчеркивания, но их тоже не рекомендуется использовать.

2023-02-28 17:11 UTC, vedmas commented on api/src/main/kotlin/ApiMapper.kt
> +    configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
Исправил

2023-02-28 17:11 UTC, vedmas commented on api/src/test/kotlin/RequestSerializationTest.kt
> +        assertContains(json, Regex("\"name\":\\s*\"ad title\""))
Исправил

2023-02-28 17:11 UTC, vedmas commented on common/build.gradle.kts
> +    macosX64 {}
Исправил

2023-02-28 17:11 UTC, vedmas commented on api/build.gradle.kts
> +}
Исправил

2023-02-28 17:11 UTC, vedmas commented on api/src/test/kotlin/ResponseSerializationTest.kt
> +import ru.otus.otuskotlin.marketplace.api.v1.models.*
Исправил

2023-03-22 13:32 UTC, merged